apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-frontend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: twitter
      tier: frontend
      track: stable
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: twitter
        tier: frontend
        track: stable
    spec:
      containers:
        - image: sshunnarah/twitter-frontend:${IMAGE_TAG}
          imagePullPolicy: Always
          name: twitter-frontend
          env:
            - name: TWITTER_SERVER_URL
              value: "10.0.164.116:3001"
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
